#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo Rebooting to recovery partition in 5 seconds
sleep 5

if [ "$1" = "restore" ]; then
    echo Automatic restore selected
    touch /boot/firmware/restore
fi

if [ -f "/boot/firmware/custom.toml.bak" ]; then
    mv /boot/firmware/custom.toml.bak /boot/firmware/custom.toml
    sed -i '1{s|$| init=/usr/lib/raspberrypi-sys-mods/firstboot|}' /boot/firmware/cmdline.txt
fi

sed -i 's/mmcblk0p3/mmcblk0p2/' /boot/firmware/cmdline.txt

reboot

exit 0
