#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo Rebooting to root partition in 5 seconds
sleep 5

sed -i 's/mmcblk0p2/mmcblk0p3/' /boot/firmware/cmdline.txt

reboot
exit 0
