#!/bin/bash
if [ -f "/boot/firmware/restore" ]; then
    echo Restoring rootfs
    dd if=/rootfs.img of=/dev/mmcblk0p3 conv=fsync status=progress bs=4M
    unlink /boot/firmware/restore
    cp /boot/firmware/firstrun.bak /boot/firmware/firstrun.sh
    sed -i '1{s|$| init=/usr/lib/raspberrypi-sys-mods/firstboot systemd.run=/boot/firmware/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target|}' /boot/firmware/cmdline.txt
    /boot/firmware/boot_to_root
fi
exit 0
