#!/bin/bash
if [ -f "/boot/restore" ]; then
    echo Restoring rootfs
    dd if=/rootfs.img of=/dev/mmcblk0p3 conv=fsync status=progress bs=4M
    unlink /boot/restore
    cp /boot/firstrun.bak /boot/firstrun.sh
    sed -i '1{s|$| systemd.run=/boot/firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target|}' /boot/cmdline.txt
    /boot/boot_to_root
fi
exit 0
