# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare build
        run: |
          sudo apt-get install -y kpartx bsdtar

      - name: Create custom OS and installer files
        run: ./build_test.sh

      - name: Package installer and custom os
        run: zip -r epicOS.zip noobs

      - name: Upload artifacts for later publishing
        uses: actions/upload-artifact@v2
        with:
          name: epicOS
          path: epicOS.zip
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: epicOS 

      - name: publish
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        run: |
          mvn --settings settings.xml deploy:deploy-file \
            -DgroupId=einfachit \
            -DartifactId=epicpios \
            -Dversion=${GITHUB_REF#refs/tags/} \
            -Dpackaging=zip \
            -Dfile=epicOS.zip \
            -Durl=https://maven.pkg.github.com/einfachIT/epicPiOS/ \
            -DrepositorId:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
