# This is a basic workflow to help you get started with Actions

name: Publish Server Release

on:
  release:
    types: [released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare build
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      # Runs a set of commands using the runners shell
      - name: Create OS files
        run: ./epic-server-answers | sudo ./create_epicPiOS 

      # Create Zip file
      - name: Create Package
        run: zip -j epicServer.zip  tmp/*.restore.img

      - name: Upload artifacts for later publishing
        uses: actions/upload-artifact@v2
        with:
          name: epicServer_${{ github.event.release.tag_name }}
          path: epicServer.zip
          
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "epicServer.zip"
          folderId: ${{ secrets.UPLOAD_FOLDER_ID }}
        
